languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Loïc Houpert"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Loïc Houpert"
  image = "img/loic2web.jpg"
  # headline = "Cloud Engineer building geospatial data infrastructure <br> for Earth observation with ESA and ECMWF"
  headline = "Cloud Engineer starting a new journey in building <br> geospatial data infrastructure for Earth observation"
  bio = "I'm a cloud engineer at Development Seed focused on geospatial data infrastructure and Earth observation systems. I build cloud-native platforms and data pipelines that enable organizations to process massive satellite imagery datasets efficiently. With expertise in AWS, Terraform, Python, and Docker, I combine a decade of scientific data processing experience with modern cloud engineering practices."
  links = [
     { linkedin = "https://www.linkedin.com/in/lo%C3%AFc-h-29232037/" },
     { github = "https://github.com/lhoupert" },
     { gitlab = "https://gitlab.com/loic.houpert" },
     { google-scholar = "https://scholar.google.com/citations?user=10K7fIYAAAAJ&hl=en" },
     { stack-overflow = "https://stackoverflow.com/users/13890678/lhoupert" },
     { email = "mailto:loic@lhoupert.fr" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },

  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { kofi = "https://ko-fi.com/username" },
  #   { lastfm = "https://lastfm.com/user/username" },

  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
     #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  #   { xing = "https://xing.com/profile/username" },
  ]
